# Site settings
title: Nicholas Rees
header-img: img/newfivesmall.jpg
footer-img: img/newfivefloor.jpg
contact-img: img/fifteen.jpg
subtitle: "Hello!"
email: nicholas.rees@live.co.uk
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://www.nprees.com"
avatar: img/profile.jpg
email_address: nick@nprees.com
twitter_username: nprees
linkedin_username:  nprees

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]