title: Nicholas Rees
description: Recent computer science graduate. Passionate about big data visualisation.

url: http://nprees.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: nprees
   twitter: nprees
   email: nicholas.rees@live.co.uk

google_analytics: "UA-58263416-1"
