# Site settings
title: Nicholas Rees
header-img: img/four.jpeg
email: nicholas.rees@live.co.uk
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://nprees.github.io"
twitter_username: nprees
github_username:  nprees
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
