# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
<<<<<<< HEAD
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
=======

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: nprees
   linkedin: nprees
   twitter: nprees
   email: nicholas.rees@live.co.uk

google_analytics: "UA-58263416-1"
>>>>>>> origin/master
